# This is a simple example of using a config map to create a single page static site.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "grpc.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "grpc.name" . }}
data:
  zipkin-host: {{ .Values.configmap.zipkinHost }}
  zipkin-port: {{ .Values.configmap.zipkinPort | quote }}