kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: grpc-volume-claim
spec:
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 5Gi
 storageClassName: slow
 selector:
  name: grpc-volume