kind: DeploymentConfig
apiVersion: v1
metadata:
  generation: 2
  labels:
    app: grpc
    deployconfig: grpc-deploy
  name: grpc
  namespace: myproject
spec:
  replicas: 2
  selector:
    app: grpc
    deployconfig: grpc-deploy
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: grpc
        deployconfig: grpc-deploy
    spec:
      containers:
        - image: "norse:5000/person-grpc:1.4"
          imagePullPolicy: IfNotPresent
          name: grpc
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data/files
              name: person-grpc-volume-1
          env:
            - name: TZ
              value: Asia/Singapore
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
          - name: person-grpc-volume-1
            persistentVolumeClaim:
              claimName: person-grpc-volume-claim
  test: false
  triggers:
    - type: ConfigChange