grpc:
    port : 50051

logging:
  level:
    ROOT: INFO

zipkin:
  nodePort: 30002
  external-host: 192.168.99.100
  #oc config
  #service-host: zipkin-service.myproject.svc
  service-host: zipkin.my-project

person-service:
  external-host: 192.168.99.100
  external-port: 30001
