---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: grpc
  namespace: my-project
  labels:
    run: grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      run: grpc
  template:
    metadata:
      labels:
        run: grpc
    spec:
      containers:
      - name: grpc
        image: grpc:1.6
        ports:
        - containerPort: 50051
          protocol: TCP
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
